config/routes.rb
Homotalk::Application.routes.draw do
  resources :places

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  post "users/verify" => 'users#verify'

  get "find" => 'places#find', :as => :find

  post "text/incoming" => 'text#incoming'

  root 'home#index'

end

app/models/place.rb
class Place < ActiveRecord::Base
  scope :wifi, -> { where(category: 'Wifi') }
  scope :hang, -> { where(category: 'Hang') }
  scope :sleep, -> { where(category: 'Sleep') }

  geocoded_by :address
  before_save :geocode

  def self.localize(text_location)
    unless text_location.match(/SF|San Francisco/)
      text_location.concat(", San Francisco")
    end
    return text_location
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  def find
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render action: 'show', status: :created, location: @place }
      else
        format.html { render action: 'new' }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :hours, :info, :address, :latitude, :longitude, :category)
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= form_for(@place) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this spot from being saved:</h2>

      <ul>
      <% @place.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :hours %><br>
    <%= f.text_field :hours %>
  </div>
  <div class="field">
    <%= f.label :info %><br>
    <%= f.text_field :info %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.select(:category, [['wifi','Wifi'],['hang','Hang'],['sleep','Sleep']]) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Edit This Spot</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/find.html.erb
<h1>Find A Spot</h1>

<%= form_tag("/find", method: "get") do %>

  <%= # What? %>
  <%= label_tag(:type, "I&rsquo;m looking for") %>
  <%= text_field_tag(:type) %>

  <%= # Where? %>
  <%= label_tag(:location, "Near") %>
  <%= text_field_tag(:location) %>
  or <button>me</button>

  <%= # When? %>
  <%= select_tag(:hours, options_for_select([['now', 'now'], ['today', 'today'], ['tonight','tonight'],['whenever','whenever']])) %>

  <%= submit_tag %>

<% end %>

app/views/places/index.html.erb
<div class="masthead">
  <h1 class="page-title">See All Spots</h1>
  <div class="controls">
    <h3>Show good spots for:</h3>
    <ul class="categories">
      <li><a href="#" class="category-wifi">wifi</a></li>
      <li><a href="#" class="category-hang">hang</a></li>
      <li><a href="#" class="category-sleep">sleep</a></li>
    </ul>
  </div>
  <div class="add">
    <h3><span class="button"><%= link_to 'Add a spot', new_place_path %></span></h3>
  </div>
</div>

<div id="map"></div>
<script>
  var map = L.mapbox.map('map', 'unruthless.gc5l92e0');
  var places = JSON.parse('<%= j @places.to_json.html_safe %>');
  for(var i = 0; i < places.length; i++){
    p = places[i].place;
    L.marker([ p.latitude, p.longitude]).addTo(map);
  }
</script>

<table class="listings" cellspacing="0">
  <thead>
    <tr>
      <th>Name</th>
      <th>Hours</th>
      <th>Info</th>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Category</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.name %></td>
        <td><%= place.hours %></td>
        <td><%= place.info %></td>
        <td><%= place.address %></td>
        <td><%= place.latitude %></td>
        <td><%= place.longitude %></td>
        <td><%= place.category %></td>
        <td><span class="button"><%= link_to 'Show', place %></span></td>
        <td><span class="button"><%= link_to 'Edit', edit_place_path(place) %></span></td>
        <td><span class="button"><%= link_to 'Delete', place, method: :delete, data: { confirm: 'Are you sure?' } %></span></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/places/new.html.erb
<h1>Add A Spot</h1>

<%= render 'form' %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @place.name %>
</p>

<p>
  <strong>Hours:</strong>
  <%= @place.hours %>
</p>

<p>
  <strong>Info:</strong>
  <%= @place.info %>
</p>

<p>
  <strong>Address:</strong>
  <%= @place.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @place.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @place.longitude %>
</p>

<p>
  <strong>Category:</strong>
  <%= @place.category %>
</p>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>